((array (("system-class" "array")
         ("type" "simple-array")
         ("system-class" "vector")
         ("type" "simple-vector")
         ("system-class" "bit-vector")
         ("type" "simple-bit-vector")
         ("function" "make-array")
         ("function" "adjust-array")
         ("function" "adjustable-array-p")
         ("accessor" "aref")
         ("function" "array-dimension")
         ("function" "array-dimensions")
         ("function" "array-element-type")
         ("function" "array-has-fill-pointer-p")
         ("function" "array-displacement")
         ("function" "array-in-bounds-p")
         ("function" "array-rank")
         ("function" "array-row-major-index")
         ("function" "array-total-size")
         ("function" "arrayp")
         ("accessor" "fill-pointer")
         ("accessor" "row-major-aref")
         ("function" "upgraded-array-element-type")
         ("constant" "array-dimension-limit")
         ("constant" "array-rank-limit")
         ("constant" "array-total-size-limit")
         ("function" "simple-vector-p")
         ("accessor" "svref")
         ("function" "vector")
         ("function" "vector-pop")
         ("function" "vector-push" "vector-push-extend")
         ("function" "vectorp")
         ("accessor" "bit" "sbit")
         ("function" "bit-and" "bit-andc1" "bit-andc2" "bit-eqv" "bit-ior" "bit-nand" "bit-nor" "bit-not" "bit-orc1" "bit-orc2" "bit-xor")
         ("function" "bit-vector-p")
         ("function" "simple-bit-vector-p")))
 (character (("system-class" "character")
             ("type" "base-char")
             ("type" "standard-char")
             ("type" "extended-char")
             ("function" "char=" "char/=" "char<" "char>" "char<=" "char>=" "char-equal" "char-not-equal" "char-lessp" "char-greaterp" "char-not-greaterp" "char-not-lessp")
             ("function" "character")
             ("function" "characterp")
             ("function" "alpha-char-p")
             ("function" "alphanumericp")
             ("function" "digit-char")
             ("function" "digit-char-p")
             ("function" "graphic-char-p")
             ("function" "standard-char-p")
             ("function" "char-upcase" "char-downcase")
             ("function" "upper-case-p" "lower-case-p" "both-case-p")
             ("function" "char-code")
             ("function" "char-int")
             ("function" "code-char")
             ("constant" "char-code-limit")
             ("function" "char-name")
             ("function" "name-char")))
 (condition (("condition-type" "condition")
             ("condition-type" "warning" )
             ("condition-type" "style-warning" )
             ("condition-type" "serious-condition")
             ("condition-type" "error")
             ("condition-type" "cell-error")
             ("function" "cell-error-name")
             ("condition-type" "parse-error")
             ("condition-type" "storage-condition")
             ("macro" "assert")
             ("function" "error")
             ("function" "cerror")
             ("macro" "check-type")
             ("condition-type" "simple-error")
             ("function" "invalid-method-error")
             ("function" "method-combination-error")
             ("function" "signal")
             ("condition-type" "simple-condition")
             ("function" "simple-condition-format-control" "simple-condition-format-arguments")
             ("function" "warn")
             ("condition-type" "simple-warning")
             ("function" "invoke-debugger")
             ("function" "break")
             ("variable" "*debugger-hook*")
             ("variable" "*break-on-signals*")
             ("macro" "handler-bind")
             ("macro" "handler-case")
             ("macro" "ignore-errors")
             ("macro" "define-condition")
             ("function" "make-condition")
             ("system-class" "restart")
             ("function" "compute-restarts")
             ("function" "find-restart")
             ("function" "invoke-restart")
             ("function" "invoke-restart-interactively")
             ("macro" "restart-bind")
             ("macro" "restart-case")
             ("function" "restart-name")
             ("macro" "with-condition-restarts")
             ("macro" "with-simple-restart")
             ("restart" "abort")
             ("restart" "continue")
             ("restart" "muffle-warning")
             ("restart" "store-value")
             ("restart" "use-value")
             ("function" "abort" "continue" "muffle-warning" "store-value" "use-value")))
 (conses (("system-class" "list")
          ("system-class" "null")
          ("system-class" "cons")
          ("type" "atom")
          ("function" "cons")
          ("function" "consp")
          ("function" "atom")
          ("function" "rplaca" "rplacd")
          ("accessor" "car" "cdr" "caar" "cadr" "cdar" "cddr" "caaar" "caadr" "cadar" "caddr" "cdaar" "cdadr" "cddar" "cdddr" "caaaar" "caaadr" "caadar" "caaddr" "cadaar" "cadadr" "caddar" "cadddr" "cdaaar" "cdaadr" "cdadar" "cdaddr" "cddaar" "cddadr" "cdddar" "cddddr")
          ("function" "copy-tree")
          ("function" "sublis" "nsublis")
          ("function" "subst" "subst-if" "subst-if-not" "nsubst" "nsubst-if" "nsubst-if-not")
          ("function" "tree-equal")
          ("function" "copy-list")
          ("function" "list" "list*")
          ("function" "list-length")
          ("function" "listp")
          ("function" "make-list")
          ("macro" "push")
          ("macro" "pop")
          ("accessor" "first" "second" "third" "fourth" "fifth" "sixth" "seventh" "eighth" "ninth" "tenth")
          ("accessor" "nth")
          ("function" "endp")
          ("function" "null")
          ("function" "nconc")
          ("function" "append")
          ("function" "revappend" "nreconc")
          ("function" "butlast" "nbutlast")
          ("function" "last")
          ("function" "ldiff" "tailp")
          ("function" "nthcdr")
          ("accessor" "rest")
          ("function" "member" "member-if" "member-if-not")
          ("function" "mapc" "mapcar" "mapcan" "mapl" "maplist" "mapcon")
          ("function" "acons")
          ("function" "assoc" "assoc-if" "assoc-if-not")
          ("function" "copy-alist")
          ("function" "pairlis")
          ("function" "rassoc" "rassoc-if" "rassoc-if-not")
          ("function" "get-properties")
          ("accessor" "getf")
          ("macro" "remf")
          ("function" "intersection" "nintersection")
          ("function" "adjoin")
          ("macro" "pushnew")
          ("function" "set-difference" "nset-difference")
          ("function" "set-exclusive-or" "nset-exclusive-or")
          ("function" "subsetp")
          ("function" "union" "nunion")))
 (control-flow (("function" "apply")
                ("macro" "defun")
                ("accessor" "fdefinition")
                ("function" "fboundp")
                ("function" "fmakunbound")
                ("special-operator" "flet" "labels" "macrolet")
                ("function" "funcall")
                ("special-operator" "function")
                ("function" "function-lambda-expression")
                ("function" "functionp")
                ("function" "compiled-function-p")
                ("constant" "call-arguments-limit")
                ("constant" "lambda-list-keywords")
                ("constant" "lambda-parameters-limit")
                ("macro" "defconstant")
                ("macro" "defparameter" "defvar")
                ("macro" "destructuring-bind")
                ("special-operator" "let" "let*")
                ("special-operator" "progv")
                ("special-form" "setq")
                ("macro" "psetq")
                ("special-operator" "block")
                ("special-operator" "catch")
                ("special-operator" "go")
                ("special-operator" "return-from")
                ("macro" "return")
                ("special-operator" "tagbody")
                ("special-operator" "throw")
                ("special-operator" "unwind-protect")
                ("constant" "nil")
                ("function" "not")
                ("constant" "t")
                ("function" "eq")
                ("function" "eql")
                ("function" "equal")
                ("function" "equalp")
                ("function" "identity")
                ("function" "complement")
                ("function" "constantly")
                ("function" "every" "some" "notevery" "notany")
                ("macro" "and")
                ("macro" "cond")
                ("special-operator" "if")
                ("macro" "or")
                ("macro" "when" "unless")
                ("macro" "case" "ccase" "ecase")
                ("macro" "typecase" "ctypecase" "etypecase")
                ("macro" "multiple-value-bind")
                ("special-operator" "multiple-value-call")
                ("macro" "multiple-value-list")
                ("special-operator" "multiple-value-prog1")
                ("macro" "multiple-value-setq")
                ("accessor" "values")
                ("function" "values-list")
                ("constant" "multiple-values-limit")
                ("macro" "nth-value")
                ("macro" "prog" "prog*")
                ("macro" "prog1" "prog2")
                ("special-operator" "progn")
                ("macro" "define-modify-macro")
                ("macro" "defsetf")
                ("macro" "define-setf-expander")
                ("function" "get-setf-expansion")
                ("macro" "setf" "psetf")
                ("macro" "shiftf")
                ("macro" "rotatef")
                ("condition-type" "control-error")
                ("condition-type" "program-error")
                ("condition-type" "undefined-function")))
 (environment (("function" "decode-universal-time")
               ("function" "encode-universal-time")
               ("function" "get-universal-time" "get-decoded-time")
               ("function" "sleep")
               ("function" "apropos" "apropos-list")
               ("function" "describe")
               ("generic" "describe-object")
               ("macro" "trace" "untrace")
               ("macro" "step")
               ("macro" "time")
               ("constant" "internal-time-units-per-second")
               ("function" "get-internal-real-time")
               ("function" "get-internal-run-time")
               ("function" "disassemble")
               ("generic" "documentation" "(setf documentation)")
               ("function" "room")
               ("function" "ed")
               ("function" "inspect")
               ("function" "dribble")
               ("variable" "-")
               ("variable" "+" "++" "+++")
               ("variable" "*" "**" "***")
               ("variable" "/" "//" "///")
               ("function" "lisp-implementation-type" "lisp-implementation-version")
               ("function" "short-site-name" "long-site-name")
               ("function" "machine-instance")
               ("function" "machine-type")
               ("function" "machine-version")
               ("function" "software-type" "software-version")
               ("function" "user-homedir-pathname")))
 (evaluation (("symbol" "lambda")
              ("macro" "lambda" )
              ("function" "compile")
              ("function" "eval")
              ("special-operator" "eval-when")
              ("special-operator" "load-time-value")
              ("special-operator" "quote")
              ("accessor" "compiler-macro-function")
              ("macro" "define-compiler-macro")
              ("macro" "defmacro")
              ("accessor" "macro-function")
              ("function" "macroexpand" "macroexpand-1")
              ("macro" "define-symbol-macro" )
              ("special-operator" "symbol-macrolet")
              ("variable" "*macroexpand-hook*")
              ("function" "proclaim")
              ("macro" "declaim")
              ("symbol" "declare")
              ("declaration" "ignore" "ignorable")
              ("declaration" "dynamic-extent")
              ("declaration" "type")
              ("declaration" "inline" "notinline")
              ("declaration" "ftype")
              ("declaration" "declaration")
              ("declaration" "optimize")
              ("declaration" "special")
              ("special-operator" "locally")
              ("special-operator" "the")
              ("function" "special-operator-p")
              ("function" "constantp")))
 (filename (("system-class" "pathname")
            ("system-class" "logical-pathname")
            ("function" "pathname")
            ("function" "make-pathname")
            ("function" "pathnamep")
            ("function" "pathname-host" "pathname-device" "pathname-directory" "pathname-name" "pathname-type" "pathname-version")
            ("function" "load-logical-pathname-translations")
            ("accessor" "logical-pathname-translations")
            ("function" "logical-pathname")
            ("variable" "*default-pathname-defaults*")
            ("function" "namestring" "file-namestring" "directory-namestring" "host-namestring" "enough-namestring")
            ("function" "parse-namestring")
            ("function" "wild-pathname-p")
            ("function" "pathname-match-p")
            ("function" "translate-logical-pathname")
            ("function" "translate-pathname")
            ("function" "merge-pathnames")))
 (file (("function" "directory")
        ("function" "probe-file")
        ("function" "ensure-directories-exist")
        ("function" "truename")
        ("function" "file-author")
        ("function" "file-write-date")
        ("function" "rename-file")
        ("function" "delete-file")
        ("condition-type" "file-error")
        ("function" "file-error-pathname")))
 (hash-table (("system-class" "hash-table")
              ("function" "make-hash-table")
              ("function" "hash-table-p")
              ("function" "hash-table-count")
              ("function" "hash-table-rehash-size")
              ("function" "hash-table-rehash-threshold")
              ("function" "hash-table-size")
              ("function" "hash-table-test")
              ("accessor" "gethash")
              ("function" "remhash")
              ("function" "maphash")
              ("macro" "with-hash-table-iterator")
              ("function" "clrhash")
              ("function" "sxhash")))
 (iteration (("macro" "do" "do*")
             ("macro" "dotimes")
             ("macro" "dolist")
             ("macro" "loop")
             ("local-macro" "loop-finish")))
 (number (("system-class" "number")
          ("system-class" "complex")
          ("system-class" "real")
          ("system-class" "float")
          ("type" "short-float" "single-float" "double-float" "long-float")
          ("system-class" "rational")
          ("system-class" "ratio")
          ("system-class" "integer")
          ("type" "signed-byte")
          ("type" "unsigned-byte")
          ("type-specifier" "mod")
          ("type" "bit")
          ("type" "fixnum")
          ("type" "bignum")
          ("function" "=" "/=" "<" ">" "<=" ">=")
          ("function" "max" "min")
          ("function" "minusp" "plusp")
          ("function" "zerop")
          ("function" "floor" "ffloor" "ceiling" "fceiling" "truncate" "ftruncate" "round" "fround")
          ("function" "sin" "cos" "tan")
          ("function" "asin" "acos" "atan")
          ("constant" "pi")
          ("function" "sinh" "cosh" "tanh" "asinh" "acosh" "atanh")
          ("function" "*")
          ("function" "+")
          ("function" "-")
          ("function" "/")
          ("function" "1+" "1-")
          ("function" "abs")
          ("function" "evenp" "oddp")
          ("function" "exp" "expt")
          ("function" "gcd")
          ("macro" "incf" "decf")
          ("function" "lcm")
          ("function" "log")
          ("function" "mod" "rem")
          ("function" "signum")
          ("function" "sqrt" "isqrt")
          ("system-class" "random-state")
          ("function" "make-random-state")
          ("function" "random")
          ("function" "random-state-p")
          ("variable" "*random-state*")
          ("function" "numberp")
          ("function" "cis")
          ("function" "complex")
          ("function" "complexp")
          ("function" "conjugate")
          ("function" "phase")
          ("function" "realpart" "imagpart")
          ("function" "upgraded-complex-part-type")
          ("function" "realp")
          ("function" "numerator" "denominator")
          ("function" "rational" "rationalize")
          ("function" "rationalp")
          ("function" "ash")
          ("function" "integer-length")
          ("function" "integerp")
          ("function" "parse-integer")
          ("function" "boole")
          ("constant" "boole-1" "boole-2" "boole-and" "boole-andc1" "boole-andc2" "boole-c1" "boole-c2" "boole-clr" "boole-eqv" "boole-ior" "boole-nand" "boole-nor" "boole-orc1" "boole-orc2" "boole-set" "boole-xor")
          ("function" "logand" "logandc1" "logandc2" "logeqv" "logior" "lognand" "lognor" "lognot" "logorc1" "logorc2" "logxor")
          ("function" "logbitp")
          ("function" "logcount")
          ("function" "logtest")
          ("function" "byte" "byte-size" "byte-position")
          ("function" "deposit-field")
          ("function" "dpb")
          ("accessor" "ldb")
          ("function" "ldb-test")
          ("accessor" "mask-field")
          ("constant" "most-positive-fixnum" "most-negative-fixnum")
          ("function" "decode-float" "scale-float" "float-radix" "float-sign" "float-digits" "float-precision" "integer-decode-float")
          ("function" "float")
          ("function" "floatp")
          ("constant" "most-positive-short-float" "least-positive-short-float" "least-positive-normalized-short-float" "most-positive-double-float" "least-positive-double-float" "least-positive-normalized-double-float" "most-positive-long-float" "least-positive-long-float" "least-positive-normalized-long-float" "most-positive-single-float" "least-positive-single-float" "least-positive-normalized-single-float" "most-negative-short-float" "least-negative-short-float" "least-negative-normalized-short-float" "most-negative-single-float" "least-negative-single-float" "least-negative-normalized-single-float" "most-negative-double-float" "least-negative-double-float" "least-negative-normalized-double-float" "most-negative-long-float" "least-negative-long-float" "least-negative-normalized-long-float")
          ("constant" "short-float-epsilon" "short-float-negative-epsilon" "single-float-epsilon" "single-float-negative-epsilon" "double-float-epsilon" "double-float-negative-epsilon" "long-float-epsilon" "long-float-negative-epsilon")
          ("condition-type" "arithmetic-error")
          ("function" "arithmetic-error-operands" "arithmetic-error-operation")
          ("condition-type" "division-by-zero")
          ("condition-type" "floating-point-invalid-operation")
          ("condition-type" "floating-point-inexact")
          ("condition-type" "floating-point-overflow")
          ("condition-type" "floating-point-underflow")))
 (object (("generic" "function-keywords")
          ("function" "ensure-generic-function")
          ("generic" "allocate-instance")
          ("generic" "reinitialize-instance")
          ("generic" "shared-initialize")
          ("generic" "update-instance-for-different-class")
          ("generic" "update-instance-for-redefined-class")
          ("generic" "change-class")
          ("function" "slot-boundp")
          ("function" "slot-exists-p")
          ("function" "slot-makunbound")
          ("generic" "slot-missing")
          ("generic" "slot-unbound")
          ("function" "slot-value")
          ("generic" "method-qualifiers")
          ("generic" "no-applicable-method")
          ("generic" "no-next-method")
          ("generic" "remove-method")
          ("generic" "make-instance")
          ("generic" "make-instances-obsolete")
          ("generic" "make-load-form")
          ("function" "make-load-form-saving-slots")
          ("macro" "with-accessors")
          ("macro" "with-slots")
          ("macro" "defclass")
          ("macro" "defgeneric")
          ("macro" "defmethod")
          ("accessor" "find-class")
          ("local-function" "next-method-p")
          ("local-macro" "call-method" "make-method")
          ("local-function" "call-next-method")
          ("generic" "compute-applicable-methods")
          ("macro" "define-method-combination")
          ("generic" "find-method")
          ("generic" "add-method")
          ("generic" "initialize-instance")
          ("generic" "class-name")
          ("generic" "(setf class-name)")
          ("function" "class-of")
          ("condition-type" "unbound-slot")
          ("function" "unbound-slot-instance")))
 (package (("system-class" "package")
           ("function" "export")
           ("function" "find-symbol")
           ("function" "find-package")
           ("function" "find-all-symbols")
           ("function" "import")
           ("function" "list-all-packages")
           ("function" "rename-package")
           ("function" "shadow")
           ("function" "shadowing-import")
           ("function" "delete-package")
           ("function" "make-package")
           ("macro" "with-package-iterator")
           ("function" "unexport")
           ("function" "unintern")
           ("macro" "in-package")
           ("function" "unuse-package")
           ("function" "use-package")
           ("macro" "defpackage")
           ("macro" "do-symbols" "do-external-symbols" "do-all-symbols")
           ("function" "intern")
           ("function" "package-name")
           ("function" "package-nicknames")
           ("function" "package-shadowing-symbols")
           ("function" "package-use-list")
           ("function" "package-used-by-list")
           ("function" "packagep")
           ("variable" "*package*")
           ("condition-type" "package-error")
           ("function" "package-error-package")))
 (printer (("function" "copy-pprint-dispatch")
           ("macro" "formatter")
           ("function" "pprint-dispatch")
           ("local-macro" "pprint-exit-if-list-exhausted")
           ("function" "pprint-fill" "pprint-linear" "pprint-tabular")
           ("function" "pprint-indent")
           ("macro" "pprint-logical-block")
           ("function" "pprint-newline")
           ("local-macro" "pprint-pop")
           ("function" "pprint-tab")
           ("generic" "print-object")
           ("macro" "print-unreadable-object")
           ("function" "set-pprint-dispatch")
           ("function" "write" "prin1" "print" "pprint" "princ")
           ("function" "write-to-string" "prin1-to-string" "princ-to-string")
           ("variable" "*print-array*")
           ("variable" "*print-base*" "*print-radix*")
           ("variable" "*print-case*")
           ("variable" "*print-circle*")
           ("variable" "*print-escape*")
           ("variable" "*print-gensym*")
           ("variable" "*print-level*" "*print-length*")
           ("variable" "*print-lines*")
           ("variable" "*print-miser-width*")
           ("variable" "*print-pprint-dispatch*")
           ("variable" "*print-pretty*")
           ("variable" "*print-readably*")
           ("variable" "*print-right-margin*")
           ("condition-type" "print-not-readable")
           ("function" "print-not-readable-object")
           ("function" "format")))
 (reader (("system-class" "readtable")
          ("function" "copy-readtable")
          ("function" "make-dispatch-macro-character")
          ("function" "read" "read-preserving-whitespace")
          ("function" "read-delimited-list")
          ("function" "read-from-string")
          ("accessor" "readtable-case")
          ("function" "readtablep")
          ("function" "set-dispatch-macro-character" "get-dispatch-macro-character")
          ("function" "set-macro-character" "get-macro-character")
          ("function" "set-syntax-from-char")
          ("macro" "with-standard-io-syntax")
          ("variable" "*read-base*")
          ("variable" "*read-default-float-format*")
          ("variable" "*read-eval*")
          ("variable" "*read-suppress*")
          ("variable" "*readtable*")
          ("condition-type" "reader-error")))
 (sequence (("system-class" "sequence")
            ("function" "copy-seq")
            ("accessor" "elt")
            ("function" "fill")
            ("function" "make-sequence")
            ("accessor" "subseq")
            ("function" "map")
            ("function" "map-into")
            ("function" "reduce")
            ("function" "count" "count-if" "count-if-not")
            ("function" "length")
            ("function" "reverse" "nreverse")
            ("function" "sort" "stable-sort")
            ("function" "find" "find-if" "find-if-not")
            ("function" "position" "position-if" "position-if-not")
            ("function" "search")
            ("function" "mismatch")
            ("function" "replace")
            ("function" "substitute" "substitute-if" "substitute-if-not" "nsubstitute" "nsubstitute-if" "nsubstitute-if-not")
            ("function" "concatenate")
            ("function" "merge")
            ("function" "remove" "remove-if" "remove-if-not" "delete" "delete-if" "delete-if-not")
            ("function" "remove-duplicates" "delete-duplicates")))
 (stream (("system-class" "stream")
          ("system-class" "broadcast-stream")
          ("system-class" "concatenated-stream")
          ("system-class" "echo-stream")
          ("system-class" "file-stream")
          ("system-class" "string-stream")
          ("system-class" "synonym-stream")
          ("system-class" "two-way-stream")
          ("function" "input-stream-p" "output-stream-p")
          ("function" "interactive-stream-p")
          ("function" "open-stream-p")
          ("function" "stream-element-type")
          ("function" "streamp")
          ("function" "read-byte")
          ("function" "write-byte")
          ("function" "peek-char")
          ("function" "read-char")
          ("function" "read-char-no-hang")
          ("function" "terpri" "fresh-line")
          ("function" "unread-char")
          ("function" "write-char")
          ("function" "read-line")
          ("function" "write-string" "write-line")
          ("function" "read-sequence")
          ("function" "write-sequence")
          ("function" "file-length")
          ("function" "file-position")
          ("function" "file-string-length")
          ("function" "open")
          ("function" "stream-external-format")
          ("macro" "with-open-file")
          ("function" "close")
          ("macro" "with-open-stream")
          ("function" "listen")
          ("function" "clear-input")
          ("function" "finish-output" "force-output" "clear-output")
          ("function" "y-or-n-p" "yes-or-no-p")
          ("function" "make-synonym-stream")
          ("function" "synonym-stream-symbol")
          ("function" "broadcast-stream-streams")
          ("function" "make-broadcast-stream")
          ("function" "make-two-way-stream")
          ("function" "two-way-stream-input-stream" "two-way-stream-output-stream")
          ("function" "echo-stream-input-stream" "echo-stream-output-stream")
          ("function" "make-echo-stream")
          ("function" "concatenated-stream-streams")
          ("function" "make-concatenated-stream")
          ("function" "get-output-stream-string")
          ("function" "make-string-input-stream")
          ("function" "make-string-output-stream")
          ("macro" "with-input-from-string")
          ("macro" "with-output-to-string")
          ("variable" "*debug-io*" "*error-output*" "*query-io*" "*standard-input*" "*standard-output*" "*trace-output*")
          ("variable" "*terminal-io*")
          ("condition-type" "stream-error")
          ("function" "stream-error-stream")
          ("condition-type" "end-of-file")))
 (string (("system-class" "string")
          ("type" "base-string")
          ("type" "simple-string" )
          ("type" "simple-base-string")
          ("function" "simple-string-p")
          ("accessor" "char" "schar")
          ("function" "string")
          ("function" "string-upcase" "string-downcase" "string-capitalize" "nstring-upcase" "nstring-downcase" "nstring-capitalize")
          ("function" "string-trim" "string-left-trim" "string-right-trim")
          ("function" "string=" "string/=" "string<" "string>" "string<=" "string>=" "string-equal" "string-not-equal" "string-lessp" "string-greaterp" "string-not-greaterp" "string-not-lessp")
          ("function" "stringp")
          ("function" "make-string")))
 (structure (("macro" "defstruct")
             ("function" "copy-structure")))
 (symbol (("system-class" "symbol")
          ("type" "keyword")
          ("function" "symbolp")
          ("function" "keywordp")
          ("function" "make-symbol")
          ("function" "copy-symbol")
          ("function" "gensym")
          ("variable" "*gensym-counter*")
          ("function" "gentemp")
          ("accessor" "symbol-function")
          ("function" "symbol-name")
          ("function" "symbol-package")
          ("accessor" "symbol-plist")
          ("accessor" "symbol-value")
          ("accessor" "get")
          ("function" "remprop")
          ("function" "boundp")
          ("function" "makunbound")
          ("function" "set")
          ("condition-type" "unbound-variable")))
 (system (("function" "compile-file")
          ("function" "compile-file-pathname")
          ("function" "load")
          ("macro" "with-compilation-unit")
          ("variable" "*features*")
          ("variable" "*compile-file-pathname*" "*compile-file-truename*")
          ("variable" "*load-pathname*" "*load-truename*")
          ("variable" "*compile-print*" "*compile-verbose*")
          ("variable" "*load-print*" "*load-verbose*")
          ("variable" "*modules*")
          ("function" "provide" "require")))
 (types (("type" "nil")
         ("type" "boolean")
         ("system-class" "function")
         ("type" "compiled-function")
         ("system-class" "generic-function")
         ("system-class" "standard-generic-function")
         ("system-class" "class")
         ("system-class" "built-in-class")
         ("system-class" "structure-class")
         ("system-class" "standard-class")
         ("system-class" "method")
         ("system-class" "standard-method")
         ("class" "structure-object")
         ("class" "standard-object")
         ("system-class" "method-combination")
         ("system-class" "t")
         ("type-specifier" "satisfies")
         ("type-specifier" "member")
         ("type-specifier" "not")
         ("type-specifier" "and")
         ("type-specifier" "or")
         ("type-specifier" "values")
         ("type-specifier" "eql")
         ("function" "coerce")
         ("macro" "deftype")
         ("function" "subtypep")
         ("function" "type-of")
         ("function" "typep")
         ("condition-type" "type-error")
         ("function" "type-error-datum" "type-error-expected-type")
         ("condition-type" "simple-type-error"))))
